config/routes.rb
Rails.application.routes.draw do
  resources :wishes
  resources :nondas
  resources :stocks
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nonda.rb
class Nonda < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
end

app/models/wish.rb
class Wish < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nondas_controller.rb
class NondasController < ApplicationController
  before_action :set_nonda, only: [:show, :edit, :update, :destroy]

  # GET /nondas
  # GET /nondas.json
  def index
    @nondas = Nonda.all
  end

  # GET /nondas/1
  # GET /nondas/1.json
  def show
  end

  # GET /nondas/new
  def new
    @nonda = Nonda.new
  end

  # GET /nondas/1/edit
  def edit
  end

  # POST /nondas
  # POST /nondas.json
  def create
    @nonda = Nonda.new(nonda_params)

    respond_to do |format|
      if @nonda.save
        format.html { redirect_to @nonda, notice: 'Nonda was successfully created.' }
        format.json { render :show, status: :created, location: @nonda }
      else
        format.html { render :new }
        format.json { render json: @nonda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nondas/1
  # PATCH/PUT /nondas/1.json
  def update
    respond_to do |format|
      if @nonda.update(nonda_params)
        format.html { redirect_to @nonda, notice: 'Nonda was successfully updated.' }
        format.json { render :show, status: :ok, location: @nonda }
      else
        format.html { render :edit }
        format.json { render json: @nonda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nondas/1
  # DELETE /nondas/1.json
  def destroy
    @nonda.destroy
    respond_to do |format|
      format.html { redirect_to nondas_url, notice: 'Nonda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nonda
      @nonda = Nonda.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nonda_params
      params.require(:nonda).permit(:wine_name, :producer, :country, :region, :general_notes, :min_price, :max_price, :wishes_note)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:wine_name, :producer, :country, :region, :general_notes, :vintage, :price, :tasted_on, :tasted_pts, :tasting_notes)
    end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]

  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(wish_params)

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wish_params
      params.require(:wish).permit(:wine_name, :producer, :country, :region, :general_notes, :min_price, :max_price, :wishes_note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nondas_helper.rb
module NondasHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Winestock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nondas/_form.html.erb
<%= form_with(model: nonda, local: true) do |form| %>
  <% if nonda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nonda.errors.count, "error") %> prohibited this nonda from being saved:</h2>

      <ul>
        <% nonda.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_name %>
    <%= form.text_field :wine_name %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :general_notes %>
    <%= form.text_area :general_notes %>
  </div>

  <div class="field">
    <%= form.label :min_price %>
    <%= form.number_field :min_price %>
  </div>

  <div class="field">
    <%= form.label :max_price %>
    <%= form.number_field :max_price %>
  </div>

  <div class="field">
    <%= form.label :wishes_note %>
    <%= form.text_area :wishes_note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nondas/edit.html.erb
<h1>Editing Nonda</h1>

<%= render 'form', nonda: @nonda %>

<%= link_to 'Show', @nonda %> |
<%= link_to 'Back', nondas_path %>

app/views/nondas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nondas</h1>

<table>
  <thead>
    <tr>
      <th>Wine name</th>
      <th>Producer</th>
      <th>Country</th>
      <th>Region</th>
      <th>General notes</th>
      <th>Min price</th>
      <th>Max price</th>
      <th>Wishes note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nondas.each do |nonda| %>
      <tr>
        <td><%= nonda.wine_name %></td>
        <td><%= nonda.producer %></td>
        <td><%= nonda.country %></td>
        <td><%= nonda.region %></td>
        <td><%= nonda.general_notes %></td>
        <td><%= nonda.min_price %></td>
        <td><%= nonda.max_price %></td>
        <td><%= nonda.wishes_note %></td>
        <td><%= link_to 'Show', nonda %></td>
        <td><%= link_to 'Edit', edit_nonda_path(nonda) %></td>
        <td><%= link_to 'Destroy', nonda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nonda', new_nonda_path %>

app/views/nondas/new.html.erb
<h1>New Nonda</h1>

<%= render 'form', nonda: @nonda %>

<%= link_to 'Back', nondas_path %>

app/views/nondas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine name:</strong>
  <%= @nonda.wine_name %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @nonda.producer %>
</p>

<p>
  <strong>Country:</strong>
  <%= @nonda.country %>
</p>

<p>
  <strong>Region:</strong>
  <%= @nonda.region %>
</p>

<p>
  <strong>General notes:</strong>
  <%= @nonda.general_notes %>
</p>

<p>
  <strong>Min price:</strong>
  <%= @nonda.min_price %>
</p>

<p>
  <strong>Max price:</strong>
  <%= @nonda.max_price %>
</p>

<p>
  <strong>Wishes note:</strong>
  <%= @nonda.wishes_note %>
</p>

<%= link_to 'Edit', edit_nonda_path(@nonda) %> |
<%= link_to 'Back', nondas_path %>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_name %>
    <%= form.text_field :wine_name %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :general_notes %>
    <%= form.text_area :general_notes %>
  </div>

  <div class="field">
    <%= form.label :vintage %>
    <%= form.number_field :vintage %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :tasted_on %>
    <%= form.date_select :tasted_on %>
  </div>

  <div class="field">
    <%= form.label :tasted_pts %>
    <%= form.number_field :tasted_pts %>
  </div>

  <div class="field">
    <%= form.label :tasting_notes %>
    <%= form.text_area :tasting_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Wine name</th>
      <th>Producer</th>
      <th>Country</th>
      <th>Region</th>
      <th>General notes</th>
      <th>Vintage</th>
      <th>Price</th>
      <th>Tasted on</th>
      <th>Tasted pts</th>
      <th>Tasting notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.wine_name %></td>
        <td><%= stock.producer %></td>
        <td><%= stock.country %></td>
        <td><%= stock.region %></td>
        <td><%= stock.general_notes %></td>
        <td><%= stock.vintage %></td>
        <td><%= stock.price %></td>
        <td><%= stock.tasted_on %></td>
        <td><%= stock.tasted_pts %></td>
        <td><%= stock.tasting_notes %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine name:</strong>
  <%= @stock.wine_name %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @stock.producer %>
</p>

<p>
  <strong>Country:</strong>
  <%= @stock.country %>
</p>

<p>
  <strong>Region:</strong>
  <%= @stock.region %>
</p>

<p>
  <strong>General notes:</strong>
  <%= @stock.general_notes %>
</p>

<p>
  <strong>Vintage:</strong>
  <%= @stock.vintage %>
</p>

<p>
  <strong>Price:</strong>
  <%= @stock.price %>
</p>

<p>
  <strong>Tasted on:</strong>
  <%= @stock.tasted_on %>
</p>

<p>
  <strong>Tasted pts:</strong>
  <%= @stock.tasted_pts %>
</p>

<p>
  <strong>Tasting notes:</strong>
  <%= @stock.tasting_notes %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/wishes/_form.html.erb
<%= form_with(model: wish, local: true) do |form| %>
  <% if wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
        <% wish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_name %>
    <%= form.text_field :wine_name %>
  </div>

  <div class="field">
    <%= form.label :producer %>
    <%= form.text_field :producer %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :general_notes %>
    <%= form.text_area :general_notes %>
  </div>

  <div class="field">
    <%= form.label :min_price %>
    <%= form.number_field :min_price %>
  </div>

  <div class="field">
    <%= form.label :max_price %>
    <%= form.number_field :max_price %>
  </div>

  <div class="field">
    <%= form.label :wishes_note %>
    <%= form.text_area :wishes_note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing Wish</h1>

<%= render 'form', wish: @wish %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishes</h1>

<table>
  <thead>
    <tr>
      <th>Wine name</th>
      <th>Producer</th>
      <th>Country</th>
      <th>Region</th>
      <th>General notes</th>
      <th>Min price</th>
      <th>Max price</th>
      <th>Wishes note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishes.each do |wish| %>
      <tr>
        <td><%= wish.wine_name %></td>
        <td><%= wish.producer %></td>
        <td><%= wish.country %></td>
        <td><%= wish.region %></td>
        <td><%= wish.general_notes %></td>
        <td><%= wish.min_price %></td>
        <td><%= wish.max_price %></td>
        <td><%= wish.wishes_note %></td>
        <td><%= link_to 'Show', wish %></td>
        <td><%= link_to 'Edit', edit_wish_path(wish) %></td>
        <td><%= link_to 'Destroy', wish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wish', new_wish_path %>

app/views/wishes/new.html.erb
<h1>New Wish</h1>

<%= render 'form', wish: @wish %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine name:</strong>
  <%= @wish.wine_name %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @wish.producer %>
</p>

<p>
  <strong>Country:</strong>
  <%= @wish.country %>
</p>

<p>
  <strong>Region:</strong>
  <%= @wish.region %>
</p>

<p>
  <strong>General notes:</strong>
  <%= @wish.general_notes %>
</p>

<p>
  <strong>Min price:</strong>
  <%= @wish.min_price %>
</p>

<p>
  <strong>Max price:</strong>
  <%= @wish.max_price %>
</p>

<p>
  <strong>Wishes note:</strong>
  <%= @wish.wishes_note %>
</p>

<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>